### ISSUE TITLE
All Chat unavailable

### ISSUE THREAD

**Issue by kschir** [EinBaum/SuperIgnore#3]
Latest version of Superignore causes me to not be able to see any chat in the chat window. When I reverted to an earlier version the issue stopped.

**Comment by EinBaum** [comment]
I can't see the issue. Try this:

* Delete saved variables of SuperIgnore that are saved in WTF/Account/ACCOUNT/SavedVariables/SuperIgnore.lua
* Disable other addons except SuperIgnore to see if there is a conflict with another addon
* If it still doesn't work, tell me which version works
